// Auto-generated by Zorphy
// Generated at: 2026-09-02T00:00:00.000000

/// The kind of payload carried by a shared attachment.
///
/// The declaration order is the wire vocabulary: the source plugin's
/// codec encodes attachment types by index, so appending is safe but
/// reordering is a breaking change (spec 001 FR-001).
enum SharedAttachmentType {
  image,
  video,
  audio,
  file,
}
